name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - uses: sbt/setup-sbt@v1
    - name: Test
      run: sbt core/publishLocal plugin/publishLocal
